# Generated by Django 4.2.2 on 2023-06-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libros_año_pub_remove_libros_pagina_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cafe',
        ),
    ]
