# Generated by Django 4.2.2 on 2023-06-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_delete_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='año_publicacion',
            field=models.IntegerField(default=0, verbose_name='Año de publicación'),
        ),
    ]
