# Generated by Django 4.2.2 on 2023-06-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libros_año_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='paginas',
            field=models.IntegerField(verbose_name='Número de páginas'),
        ),
    ]
