# Generated by Django 4.2.2 on 2023-06-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0006_delete_libros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin nombrar', max_length=300, verbose_name='Título')),
                ('edicion', models.CharField(default='Sin especificar', max_length=300, verbose_name='Edición')),
                ('editorial', models.CharField(default='sin especificar', max_length=300, verbose_name='Editorial')),
                ('año_publicacion', models.IntegerField(default=0, verbose_name='Año de publicación')),
                ('paginas', models.IntegerField(verbose_name='Número de páginas')),
            ],
        ),
    ]
